version: '3.4'
services:
    notes:
        container_name: notes
        build: .
        ports:
            - 8000
        volumes:
            - .:/code
        networks:
            - notes-microservices-network
        depends_on:
            postgres:
                condition: service_healthy
    postgres:
        container_name: db_notes
        image: 'postgres:13'
        ports:
            - 5432
        restart: always
        volumes:
            - './postgres-data:/var/lib/postgresql/data'
        networks:
            - notes-microservices-network
        environment:
            - POSTGRES_DB=${POSTGRES_DB}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_USER=${POSTGRES_USER}
        healthcheck:
            test: ['CMD-SHELL', 'pg_isready -U postgres']
            interval: 5s
            timeout: 5s
            retries: 5
networks:
    notes-microservices-network:
        external: true
