version: "3.3"
services:
    users:
        container_name: users
        build: .
        ports:
            - 8000:8000
        volumes:
            - .:/code
        depends_on:
            postgres:
                condition: service_healthy
    postgres:
        container_name: postgres
        image: "postgres:13"
        ports:
            - "5432:5432"
        restart: always
        volumes:
            - "./postgres-data:/var/lib/postgresql/data"
        environment:
            - POSTGRES_DB=${POSTGRES_DB}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_USER=${POSTGRES_USER}
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U postgres"]
            interval: 5s
            timeout: 5s
            retries: 5
